version: "3"
services: 
  web:
    build: 
      context: ./apache-php
    ports: 
      - 80:80
    privileged: true
    links:
      - db
    volumes:
      - "./lara-d/:/var/www/html"
      - "./apache-php/apache.conf:/etc/httpd/conf/httpd.conf"
    container_name: "apache-php-pg"
  db:
    image: postgres:latest
    container_name: "postgres"
  postgres-gui:
    image: jsoizo/franchise
    links:
      - db
    ports:
      - 3000:80
    container_name: "pg-gui"
  client:
    ports: 
      - "14645:14645"
    image: "jsoizo/franchise-client"
