version: "3"
services: 
  web:
    build: 
      context: ./apache-php
    ports: 
      - 80:80
    privileged: true
    links:
      - db
    volumes:
      - "./lara-d/:/var/www/html"
      - "./apache-php/apache.conf:/etc/httpd/conf/httpd.conf"
    container_name: "apache-php-pg"
  db:
    image: postgres:latest
    container_name: "postgres"
    volumes:
      - "./postgres/:/var/www"
  postgres-gui:
    image: donnex/pgweb
    links:
      - db
    ports:
      - 8080:8080
    container_name: "pg-gui"
  # client:
  #   ports: 
  #     - "14645:14645"
  #   image: "jsoizo/franchise-client"
